using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EnumObjectID
{
    //DON'T REORDER. JUST APPEND TO THE BOTTOM.
    //OTHERWISE ENUMS ORDER WILL BE MESSED UP
    ORE,
    NPC_GRANDMA,
    NPC_KIDS,
    ZONE_TREE,
    NPC_SHOPKEEPER,
    NPC_WEAPONSMITH,
    ZONE_ABANDONED_HOUSE,
    DEMON_KING,
    NPC_VERGIL,
    NPC_SORCERESS,
    NONE,
    ZONE_SORCERESS_CHAMBERS,
    ZONE_VERGIL_ENTRANCE,
    ZONE_VERGIL_SUMMONING_CIRCLE,
    ZONE_KEEP_ENTRANCE,
    ZONE_KEEP_THRONE_BATTLE,
    ZONE_LOST_KEY,
    ZONE_KEEP_GATES,
    SIGN,
    NPC_DOG,
    NPC_CAT,
    NPC_SNAKE
}
