public enum EnumSFX
{
    SFX_NONE,
    SFX_BUTTON,
    SFX_DOOR_LOCKED,
    SFX_TALK_DEFAULT,
    SFX_QUEST_STEP_COMPLETE,
    SFX_QUEST_COMPLETE,
    SFX_ATTACK,
    SFX_ATTACK_MISS,
    SFX_DEATH,
    SFX_ENDING_DEFAULT,
    SFX_ENDING_DEAD
}